flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- gtk3-0.15.4
- hw-kafka-client-3.0.0
- strings-1.1
- gio-0.13.8.0
- cairo-0.13.8.0
- glib-0.13.8.0
- gtk2hs-buildtools-0.13.8.0
- pango-0.13.8.0

resolver: lts-15.5
allow-newer: true