flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- gtk3-0.14.8
- hw-kafka-client-2.1.3
- strings-1.1
- gio-0.13.4.0
- MissingH-1.4.0.1
- async-2.1.1.1
- bifunctors-5.4.2
- cairo-0.13.4.2
- glib-0.13.5.0
- gtk2hs-buildtools-0.13.3.1
- mtl-2.2.1
- pango-0.13.4.0
- temporary-1.2.1.1
- text-1.2.2.2
- text-conversions-0.3.0
- utf8-string-1.0.1.1
- uuid-1.3.13
- HUnit-1.6.0.0
- base-orphans-0.6
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- comonad-5.0.2
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- entropy-0.3.8
- errors-2.2.2
- exceptions-0.8.3
- hashtables-1.2.2.1
- hslogger-1.2.10
- network-2.6.3.2
- network-info-0.2.0.8
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.11
- random-1.1
- regex-compat-0.95.1
- semigroups-0.18.3
- stm-2.4.4.1
- tagged-0.8.5
- transformers-compat-0.5.1.4
- uuid-types-1.0.3
- cabal-doctest-1.0.3
- call-stack-0.1.0
- contravariant-1.4
- distributive-0.5.3
- hashable-1.2.6.1
- primitive-0.6.2.0
- regex-base-0.93.2
- regex-posix-0.95.2
- safe-0.3.15
- unexceptionalio-0.3.0
- vector-0.12.0.1
- StateVar-1.1.0.4
- void-0.7.2

resolver: nightly-2017-12-01
allow-newer: true